CREATE TABLE IF NOT EXISTS fonts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  file_path TEXT NOT NULL,
  uploaded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS font_groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS font_group_fonts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  custom_name TEXT,
  group_id INTEGER,
  font_id INTEGER,
  FOREIGN KEY(group_id) REFERENCES font_groups(id),
  FOREIGN KEY(font_id) REFERENCES fonts(id)
);
